- name: Block-Test
  hosts: web1
  gather_facts: false

  tasks:
    - name: Test1
      block:
        - name: Block-1-1
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Block-1-2
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Block-1-3
          ansible.builtin.command: /bin/false
          changed_when: true

        - name: Block-1-4
          ansible.builtin.debug:
            msg: 'I execute normally'

      rescue:
        - name: Rescue-1-1
          ansible.builtin.debug:
            msg: 'Rescue-1-1'

      always:
        - name: Always-1-1
          ansible.builtin.debug:
            msg: 'Always-1-1'

    - name: Test2
      block:
        - name: Block-2-1
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Block-2-2
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Block-2-3
          ansible.builtin.debug:
            msg: 'I execute normally'

      rescue:
        - name: Rescue-2-1
          ansible.builtin.debug:
            msg: 'Rescue-2-1'

      always:
        - name: Always-2-1
          ansible.builtin.debug:
            msg: 'Always-2-1'
