# week1

mario1:
	gcc -lcs50 -o ./output/mario ./Problem\ Set/week\ 1/p1/mario1_1.c

mario2:
	gcc -lcs50 -o ./output/mario ./Problem\ Set/week\ 1/p1/mario2_1.c

cash:
	gcc -lcs50 -o ./output/cash ./Problem\ Set/week\ 1/p2/cash.c

credit:
	gcc -lcs50 -o ./output/credit ./Problem\ Set/week\ 1/p2/credit.c

# week2

readability:
	gcc -lcs50 -o ./output/readability ./Problem\ Set/week\ 2/p1/readability_1.c

caesar:
		gcc -lcs50 -o ./output/caesar ./Problem\ Set/week\ 2/p2/caesar.c

substitution:
		gcc -lcs50 -o ./output/substitution ./Problem\ Set/week\ 2/p2/substitution.c

# week3

plurality:
		gcc -lcs50 -o ./output/plurality ./Problem\ Set/week\ 3/p1/plurality.c

runoff:
		gcc -lcs50 -o ./output/runoff ./Problem\ Set/week\ 3/p2/runoff.c

tideman:
		gcc -lcs50 -o ./output/tideman ./Problem\ Set/week\ 3/p2/tideman.c

# week4

volume: 
	gcc -o ./output/volume ./Lab/week\ 4/volume/volume.c  

filter1: 
	gcc -ggdb3 -gdwarf-4 -O0 -Qunused-arguments -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -lm -o ./output/filter ./Problem\ Set/week\ 4/p1/filter-less/filter.c ./Problem\ Set/week\ 4/p1/filter-less/helpers.c

filter2: 
	gcc -ggdb3 -gdwarf-4 -O0 -Qunused-arguments -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -lm -o ./output/filter ./Problem\ Set/week\ 4/p1/filter-more/filter.c ./Problem\ Set/week\ 4/p1/filter-more/helpers.c

recover: 
	gcc -o ./output/recover ./Problem\ Set/week\ 4/p2/recover/recover.c


