apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: '${APISERVER_IP}:${APISERVER_PORT}'
    token: '${TOKEN}'
    caCertHashes:
      - 'sha256:${HASH_VALUE}'
nodeRegistration:
  kubeletExtraArgs:
    node-ip: '${NODE_IP}'
