node_list = [
  {
    :name => "host1",
    :box => "ubuntu/trusty64"
  },
  {
    :name => "host2",
    :box => "centos/8"
  },
  {
    :name => "host3",
    :box => "generic/centos8"
  },
]


Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true, type: "virtualbox"
  config.vm.synced_folder "src/", "/vagrant/src", disabled: false, type: "virtualbox"
  config.vm.synced_folder "test/", "/vagrant/test", disabled: false, type: "virtualbox"

  node_list.each do |node|
    config.vm.define node[:name] do |host|
      host.vm.box = node[:box]
    end
  end

end
