node_list = [
  {
    :name => "worker1",
    :eth1 => "192.168.100.11"
  },
  {
    :name => "worker2",
    :eth1 => "192.168.100.12"
  },
  {
    :name => "manger1",
    :eth1 => "192.168.100.10"
  }
]


Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true, type: "virtualbox"
  config.vm.box = "ubuntu/jammy64"

  node_list.each do |node|

    config.vm.define node[:name] do |host|
      host.vm.hostname = node[:name]
      host.vm.network :private_network, ip: node[:eth1]
      
      # 使用 Ansible 作為 provisioner
      if node[:name] == "manger1"
        host.vm.synced_folder "../../../../Docker/src/code/06_Scale/", "/vagrant/src", disabled: false, type: "virtualbox"
        host.vm.provision "ansible" do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"        
          ansible.playbook = "./provision/site.yml"
        end
      end
      
    end 

  end



end



