- name: Var-Test
  hosts: web1

  vars:
    var1: '{{ var2 * 2 }}'
    var2: 1

  tasks:
    - name: Set1
      ansible.builtin.set_fact:
        var3: '{{ var2 * 2 }}'

    - name: Print1
      ansible.builtin.debug:
        msg:
          var1: '{{ var1 }}'
          var2: '{{ var2 }}'
          var3: '{{ var3 }}'
          vars:
            vars-hostvars-host-var3: '{{ vars.hostvars["ansible-node1"].var3 }}'
            vars-var1: '{{ vars.var1 }}'
            vars-var2: '{{ vars.var2 }}'
            vars-var3: '{{ vars.var3 }}'

    #         "var1": "2",
    #         "var2": 1,
    #         "var3": "2",
    #         "vars": {
    #             "vars-hostvars-host-var3": "2",
    #             "vars-var1": "{{ var2 * 2 }}",
    #             "vars-var2": "1",
    #             "vars-var3": "2"
    #         }

    - name: Set2
      ansible.builtin.set_fact:
        var3: '{{ var2 * 2 }}'
        var2: 2

    - name: Print2
      ansible.builtin.debug:
        msg:
          var1: '{{ var1 }}'
          var2: '{{ var2 }}'
          var3: '{{ var3 }}'
          vars:
            vars-hostvars-host-var2: '{{ vars.hostvars["ansible-node1"].var2 }}'
            vars-hostvars-host-var3: '{{ vars.hostvars["ansible-node1"].var3 }}'
            vars-var1: '{{ vars.var1 }}'
            vars-var2: '{{ vars.var2 }}'
            vars-var3: '{{ vars.var3 }}'

    #         "var1": "4",
    #         "var2": 2,
    #         "var3": "2",
    #         "vars": {
    #             "vars-hostvars-host-var2": "2",
    #             "vars-hostvars-host-var3": "2",
    #             "vars-var1": "{{ var2 * 2 }}",
    #             "vars-var2": "2",
    #             "vars-var3": "2"
    #         }

    - name: Set3
      ansible.builtin.set_fact:
        var3: '{{ var2 * 2 }}'

    - name: Print3
      ansible.builtin.debug:
        msg:
          var1: '{{ var1 }}'
          var2: '{{ var2 }}'
          var3: '{{ var3 }}'
          vars:
            vars-hostvars-host-var2: '{{ vars.hostvars["ansible-node1"].var2 }}'
            vars-hostvars-host-var3: '{{ vars.hostvars["ansible-node1"].var3 }}'
            vars-var1: '{{ vars.var1 }}'
            vars-var2: '{{ vars.var2 }}'
            vars-var3: '{{ vars.var3 }}'

    #         "var1": "4",
    #         "var2": 2,
    #         "var3": "4",
    #         "vars": {
    #             "vars-hostvars-host-var2": "2",
    #             "vars-hostvars-host-var3": "4",
    #             "vars-var1": "{{ var2 * 2 }}",
    #             "vars-var2": "2",
    #             "vars-var3": "4"
    #         }

    - name: Set4
      ansible.builtin.set_fact:
        var3: '{{ var2 * 2 }}'
        var1: '{{ var2 * 3 }}'
      register: set_fact4

    - name: Print4
      ansible.builtin.debug:
        msg:
          var1: '{{ var1 }}'
          var2: '{{ var2 }}'
          var3: '{{ var3 }}'
          vars:
            vars-hostvars-host-var1: '{{ vars.hostvars["ansible-node1"].var1 }}'
            vars-hostvars-host-var2: '{{ vars.hostvars["ansible-node1"].var2 }}'
            vars-hostvars-host-var3: '{{ vars.hostvars["ansible-node1"].var3 }}'
            vars-var1: '{{ vars.var1 }}'
            vars-var2: '{{ vars.var2 }}'
            vars-var3: '{{ vars.var3 }}'

    #         "var1": "6",
    #         "var2": 2,
    #         "var3": "4",
    #         "vars": {
    #             "vars-hostvars-host-var1": "6",
    #             "vars-hostvars-host-var2": "2",
    #             "vars-hostvars-host-var3": "4",
    #             "vars-var1": "6",
    #             "vars-var2": "2",
    #             "vars-var3": "4"
    #         }

    - name: Print5
      ansible.builtin.debug:
        msg:
          1-var1: '{{ var1 }}'
          1-vars:
            vars-hostvars-host-var1: '{{ vars.hostvars["ansible-node1"].var1 }}'
            vars-var1: '{{ vars.var1 }}'
            vars-hostvars-var1: '{{ vars.hostvars.var1 }}'

          2-register:
            set_fact4-changed: '{{ set_fact4.changed }}'
            vars-hostvars-set_fact4: '{{ vars.hostvars.set_fact4 }}'
            vars-hostvars-host-set_fact4-changed: '{{ vars.hostvars["ansible-node1"].set_fact4.changed }}'

          3-ansible_facts:
            vars-ansible_distribution: '{{ vars.ansible_distribution }}'
            vars-ansible_facts-distribution: '{{ vars.ansible_facts.distribution }}'
            vars-hostvars-host-ansible_facts-distribution: '{{ vars.hostvars["ansible-node1"].ansible_facts.distribution }}'

    #         "1-var1": "6",
    #         "1-vars": {
    #             "vars-hostvars-host-var1": "6",
    #             "vars-hostvars-var1": "",
    #             "vars-var1": "6"
    #         },
    #         "2-register": {
    #             "set_fact4-changed": false,
    #             "vars-hostvars-set_fact4": ""
    #             "vars-hostvars-host-set_fact4-changed": false,
    #         },
    #         "3-ansible_facts": {
    #             "vars-ansible_distribution": "Ubuntu",
    #             "vars-ansible_facts-distribution": "Ubuntu",
    #             "vars-hostvars-host-ansible_facts-distribution": "Ubuntu"
    #         }
