apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  # namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  updateStrategy:
    type: OnDelete

  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      # 若 master 也須運行，則要設定此：
      # tolerations:
      #   - key: node-role.kubernetes.io/control-plane
      #     operator: Exists
      #     effect: NoSchedule
      #   - key: node-role.kubernetes.io/master
      #     operator: Exists
      #     effect: NoSchedule

      # 若要確保運行，需另外設定 priorityClassName：
      # priorityClassName: important (需先手動建立一個 priorityClass 命名為 important)

      containers:
        - name: fluentd-elasticsearch
          image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log/test
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
