apiVersion: v1
kind: Pod
metadata:
  name: init-containers-practice2
spec:
  initContainers:
    - name: init1
      image: busybox
      command: ['sh', '-c', 'echo waiting for sercice; sleep 4']

    # init2 成為 sidecar container
    - name: init2
      image: nginx
      restartPolicy: Always ###

  containers:
    - name: client1
      image: busybox
      command:
        - sh
        - -c
        - 'sleep 1000000'
