apiVersion: v1
kind: Pod
metadata:
  name: init-containers-practice1
spec:
  initContainers:
    - name: init1
      image: busybox
      command: ['sh', '-c', 'echo waiting for sercice; sleep 4']
    - name: init2
      image: busybox
      command: ['sh', '-c', 'echo waiting for database; sleep 4']

  containers:
    - name: app-container
      image: nginx

    - name: client1
      image: busybox
      command:
        - sh
        - -c
        - 'sleep 1000000'

    - name: database
      image: mysql
